# Generated by Django 6.0.4 on 2026-04-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('website_url', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('mlm', 'MLM / Network Marketing'), ('crypto', 'Crypto / Investment'), ('survey', 'Survey / GPT'), ('freelance', 'Freelance / Remote Work'), ('forex', 'Forex / Trading'), ('dropship', 'Dropshipping / E-commerce'), ('app', 'App / Mobile Task'), ('other', 'Other')], default='other', max_length=30)),
                ('verdict', models.CharField(choices=[('scam', 'Scam'), ('legitimate', 'Legitimate'), ('suspicious', 'Suspicious'), ('unverified', 'Unverified')], default='unverified', max_length=20)),
                ('overall_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='platform_logos/')),
                ('country_of_origin', models.CharField(blank=True, max_length=100)),
                ('date_founded', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
